CREATE OR REPLACE FUNCTION INSERTA_EDUCACION_PERSONA(
  IN ID_PERSONA INTEGER,
  IN ID_EDUCACION INTEGER,
  IN FECHA_INICIO DATE,
  IN FECHA_FIN DATE,
  IN PROBATORIO VARCHAR(60)
)
  RETURNS INTEGER AS
$$
DECLARE
  ID EDUCACION_PERSONA.ID_EDUCACION_PERSONA%TYPE;
  V_ID_PERSONA  ALIAS FOR $1;
  V_ID_EDUCACION ALIAS FOR $2;
  V_FECHA_INICIO ALIAS FOR $3;
  V_FECHA_FIN ALIAS FOR $4;
  V_PROBATORIO ALIAS FOR $5;
BEGIN
  INSERT INTO EDUCACION_PERSONA(ID_PERSONA, ID_EDUCACION, FECHA_INICIO, FECHA_FIN, PROBATORIO)
  VALUES (V_ID_PERSONA, V_ID_EDUCACION, V_FECHA_INICIO, V_FECHA_FIN, V_PROBATORIO)
  RETURNING ID_EDUCACION_PERSONA INTO ID;
  RETURN ID;
END;
$$
LANGUAGE plpgsql;

--SELECT INSERTA_EDUCACION_PERSONA(1, 1, '2012-12-04', '2016-09-09', 'ARCHIVO');
