--SE OMITE FECHA FIN, PUES SE SUPONE QUE AL INSERTAR UN PUESTO SE DESCONOCE LA FECHA DE FIN
CREATE OR REPLACE FUNCTION INSERTA_PUESTO_PERSONA(
  IN ID_PERSONA INTEGER,
  IN ID_PUESTO INTEGER,
  IN FECHA_INICIO DATE
)
  RETURNS INTEGER AS
$$
DECLARE
  ID PUESTO_PERSONA.ID_PUESTO_PERSONA%TYPE;
  V_ID_PERSONA  ALIAS FOR $1;
  V_ID_PUESTO ALIAS FOR $2;
  V_FECHA_INICIO ALIAS FOR $3;
BEGIN
  INSERT INTO PUESTO_PERSONA(ID_PUESTO, ID_PERSONA, FECHA_INICIO)
  VALUES (V_ID_PUESTO, V_ID_PERSONA, V_FECHA_INICIO)
  RETURNING ID_PUESTO_PERSONA INTO ID;
  RETURN ID;
END;
$$
LANGUAGE plpgsql;

--SELECT INSERTA_PUESTO_PERSONA(1, 1, '2016-10-01');
