CREATE OR REPLACE FUNCTION INSERTA_SUBDEPARTAMENTO(
  IN ID_DEPARTAMENTO INTEGER,
  IN NOMBRE VARCHAR(50),
  IN DESCRIPCION VARCHAR(240),
  IN ABREVIACION VARCHAR(7)
)
  RETURNS INTEGER AS
$$
DECLARE
  ID SUBDEPARTAMENTO.ID_SUBDEPARTAMENTO%TYPE;
  V_ID_DEPARTAMENTO ALIAS FOR $1;
  V_NOMBRE  ALIAS FOR $2;
  V_DESCRIPCION  ALIAS FOR $3;
  V_ABREVIACION ALIAS FOR $4;
BEGIN
  INSERT INTO SUBDEPARTAMENTO(ID_DEPARTAMENTO, NOMBRE, DESCRIPCION, ABREVIACION)
  VALUES (V_ID_DEPARTAMENTO, V_NOMBRE, V_DESCRIPCION, V_ABREVIACION)
  RETURNING ID_SUBDEPARTAMENTO INTO ID;
  RETURN ID;
END;
$$
LANGUAGE plpgsql;


SELECT INSERTA_SUBDEPARTAMENTO(1, 'Instrumentación Sísmica', 'DESCRIPCION', 'ABRE');
SELECT INSERTA_SUBDEPARTAMENTO(1, 'Desarrollo e Innovación', 'DESCRIPCION', 'ABRE');
SELECT INSERTA_SUBDEPARTAMENTO(2, 'Subdirección Riesgos Inundaciones', 'DESCRIPCION', 'ABRE');
SELECT INSERTA_SUBDEPARTAMENTO(2, 'Subdirección Riesgos Volcanicos', 'DESCRIPCION', 'ABRE');
SELECT INSERTA_SUBDEPARTAMENTO(3, 'Subdirección de FOPREDEN', 'DESCRIPCION', 'ABRE');
SELECT INSERTA_SUBDEPARTAMENTO(3, 'Subdirecció Políticas Públicas', 'DESCRIPCION', 'ABRE');
