CREATE OR REPLACE FUNCTION INSERTA_GRADO(
  IN V_NOMBRE VARCHAR(70),
  IN V_DESCRIPCION VARCHAR(220),
  IN V_ABREVIACION VARCHAR(9)
)
  RETURNS INTEGER AS
$$
DECLARE
  ID GRADO.ID_GRADO%TYPE;
  NOMBRE_GRADO  ALIAS FOR $1;
  V_DESCRIPCION ALIAS FOR $2;
  V_ABREVIACION ALIAS FOR $3;
BEGIN
  INSERT INTO GRADO(NOMBRE, DESCRIPCION, ABREVIACION) VALUES (NOMBRE_GRADO, V_DESCRIPCION, V_ABREVIACION) RETURNING ID_GRADO INTO ID;
  RETURN ID;
END;
$$
LANGUAGE plpgsql;

--SELECT INSERTA_GRADO('Licenciatura','Licenciatura es el título que se obtiene tras realizar ciertos estudios de educación superior entre 4 y 6 años de duración','LIC.');
