CREATE OR REPLACE FUNCTION INSERTA_ORGANIZACION(
  IN V_NOMBRE VARCHAR(70),
  IN V_SIGLAS VARCHAR(9)
)
  RETURNS INTEGER AS
$$
DECLARE
  ID ORGANIZACION.ID_ORGANIZACION%TYPE;
  NOMBRE_ORGANIZACION  ALIAS FOR $1;
  V_SIGLAS ALIAS FOR $2;
BEGIN
  INSERT INTO organizacion(NOMBRE, SIGLAS) VALUES (NOMBRE_ORGANIZACION, V_SIGLAS) RETURNING ID_ORGANIZACION INTO ID;
  RETURN ID;
END;
$$
LANGUAGE plpgsql;

--SELECT INSERTA_ORGANIZACION('Universidad Nacional Autónoma de México', 'UNAM');
