CREATE OR REPLACE FUNCTION INSERTA_ESTADO(
  IN V_ESTADO VARCHAR(100),
  IN V_ABREVI VARCHAR(100)
)
  RETURNS INTEGER AS
$$
DECLARE
  ID ESTADO.ID_ESTADO%TYPE;
  ESTADO ALIAS FOR $1;
  ABREVI  ALIAS FOR $2;
BEGIN
  INSERT INTO ESTADO(NOMBRE, ABREVIACION) VALUES (ESTADO, ABREVI) RETURNING ID_ESTADO INTO ID;
  RETURN ID;
END;
$$
LANGUAGE plpgsql;
