CREATE OR REPLACE FUNCTION INSERTA_USUARIO(
  IN ID_PERSONA INTEGER,
  IN ID_PREGUNTA INTEGER,
  IN ID_ROL INTEGER,
  IN USUARIO VARCHAR(60),
  IN PASSWORD VARCHAR(18),
  IN RESPUESTA VARCHAR(20)
)
  RETURNS INTEGER AS
$$
DECLARE
  --ID USUARIO.ID_PERSONA%TYPE;
  V_ID_PERSONA ALIAS FOR $1;
  V_ID_PREGUNTA ALIAS FOR $2;
  V_ROL ALIAS FOR $3;
  V_USUARIO  ALIAS FOR $4;
  V_PASSWORD  ALIAS FOR $5;
  V_RESPUESTA  ALIAS FOR $6;
BEGIN
  INSERT INTO USUARIO(ID_PERSONA, ID_PREGUNTA, ID_ROL, USUARIO, PASSWORD, RESPUESTA)
  VALUES (V_ID_PERSONA, V_ID_PREGUNTA, V_ROL, V_USUARIO, V_PASSWORD, V_RESPUESTA) RETURNING ID_PERSONA INTO ID;
  RETURN ID;
END;
$$
LANGUAGE plpgsql;
