CREATE OR REPLACE FUNCTION INSERTA_PUESTO(
  IN ID_STATUS_PUESTO INTEGER,
  IN ID_TIPO_PUESTO INTEGER,
  IN ID_SUBDEPARTAMENTO INTEGER,
  IN NOMBRE VARCHAR(80),
  IN DESCRIPCION VARCHAR(140),
  IN CLAVE VARCHAR(6),
)
  RETURNS INTEGER AS
$$
DECLARE
  ID PUESTO.ID_PUESTO%TYPE;
  V_ID_STATUS_PUESTO ALIAS FOR $1;
  V_ID_TIPO_PUESTO ALIAS FOR $2;
  V_ID_SUBDEPARTAMENTO ALIAS FOR $3;
  V_NOMBRE  ALIAS FOR $4;
  V_DESCRIPCION  ALIAS FOR $5;
  V_CLAVE ALIAS FOR $6;
BEGIN
  INSERT INTO PUESTO(ID_STATUS_PUESTO, ID_TIPO_PUESTO, NOMBRE, DESCRIPCION, CLAVE, ID_SUBDEPARTAMENTO)
  VALUES (V_ID_STATUS_PUESTO, V_ID_TIPO_PUESTO, V_NOMBRE, V_DESCRIPCION, V_CLAVE, V_ID_SUBDEPARTAMENTO) RETURNING ID_PUESTO INTO ID;
  RETURN ID;
END;
$$
LANGUAGE plpgsql;

--SELECT INSERTA_PUESTO(1, 1, 1, 'Director de Desarrollo de Software', 'Jefe del  Departamento de Desarrollo de Software y Soporte Técnico', 'JDDSyT');
