CREATE OR REPLACE FUNCTION INSERTA_CURSO(
  IN V_ID_ORGANIZACION INTEGER,
  IN V_NOMBRE VARCHAR(120),
  IN DESCRIPCION VARCHAR(240)
)
  RETURNS INTEGER AS
$$
DECLARE
  ID CURSO.ID_CURSO%TYPE;
  V_ID_ORGANIZACION  ALIAS FOR $1;
  V_NOMBRE  ALIAS FOR $2;
  V_DESCRIPCION ALIAS FOR $3;
BEGIN
  INSERT INTO CURSO(ID_ORGANIZACION, NOMBRE, DESCRIPCION) VALUES (V_ID_ORGANIZACION, V_NOMBRE, V_DESCRIPCION) RETURNING ID_CURSO INTO ID;
  RETURN ID;
END;
$$
LANGUAGE plpgsql;

--SELECT INSERTA_CURSO(1, 'Diplomado Afinación de Bases de Datos', 'Facilitar los métodos, las técnicas y las herramientas para el buen diseño e implantación de base de datos.');
