CREATE OR REPLACE FUNCTION INSERTA_EMPLEADO(
  IN ID_DIRECCION INTEGER,
  IN ID_STATUS_PERSONA INTEGER,
  IN ID_SUPERIOR INTEGER,
  IN NOMBRE VARCHAR(120),
  IN AP_PATERNO VARCHAR(120),
  IN AP_MATERNO VARCHAR(120),
  IN FECHA_NACIMIENTO DATE,
  IN CURP VARCHAR(18),
  IN FOTO VARCHAR(60),
  IN NUMERO_EMPLEADO VARCHAR(9),
  IN RFC VARCHAR(13)
)
  RETURNS INTEGER AS
$$
DECLARE
  ID PERSONA.ID_PERSONA%TYPE;
  V_ID_DIRECCION ALIAS FOR $1;
  V_ID_STATUS_PERSONA ALIAS FOR $2;
  V_ID_SUPERIOR  ALIAS FOR $3;
  V_NOMBRE ALIAS FOR $4;
  V_AP_PATERNO ALIAS FOR $5;
  V_AP_MATERNO ALIAS FOR $6;
  V_FECHA_NACIMIENTO ALIAS FOR $7;
  V_CURP ALIAS FOR $8;
  V_FOTO ALIAS FOR $9;
  V_NUMERO_EMPLEADO ALIAS FOR $10;
  V_RFC ALIAS FOR $11;
BEGIN
    ID := INSERTA_PERSONA(V_ID_DIRECCION, V_ID_STATUS_PERSONA, V_ID_SUPERIOR, V_NOMBRE, V_AP_PATERNO, V_AP_MATERNO, V_FECHA_NACIMIENTO, V_CURP, 'E', V_FOTO);
    INSERT INTO EMPLEADO(ID_PERSONA, NUMERO_EMPLEADO, RFC)
    VALUES (ID, V_NUMERO_EMPLEADO, V_RFC);
  RETURN ID;
END;
$$
LANGUAGE plpgsql;

--SELECT INSERTA_EMPLEADO(1, 1, NULL, 'Ricardo Daniel', 'García', 'Aguilar', '1994-01-20', 'fafafafafafa', 'cadsasa', '345A45F3A', 'ASDAF23245');
