CREATE OR REPLACE FUNCTION INSERTA_PERSONA(
  IN ID_DIRECCION INTEGER,
  IN ID_STATUS_PERSONA INTEGER,
  IN ID_SUPERIOR INTEGER,
  IN NOMBRE VARCHAR(120),
  IN AP_PATERNO VARCHAR(120),
  IN AP_MATERNO VARCHAR(120),
  IN FECHA_NACIMIENTO DATE,
  IN CURP VARCHAR(18),
  IN TIPO_PERSONA CHAR(1),
  IN FOTO VARCHAR(60)
)
  RETURNS INTEGER AS
$$
DECLARE
  ID PERSONA.ID_PERSONA%TYPE;
  V_ID_DIRECCION ALIAS FOR $1;
  V_ID_STATUS_PERSONA ALIAS FOR $2;
  V_ID_SUPERIOR  ALIAS FOR $3;
  V_NOMBRE ALIAS FOR $4;
  V_AP_PATERNO ALIAS FOR $5;
  V_AP_MATERNO ALIAS FOR $6;
  V_FECHA_NACIMIENTO ALIAS FOR $7;
  V_CURP ALIAS FOR $8;
  V_TIPO_PERSONA ALIAS FOR $9;
  V_FOTO ALIAS FOR $10;
BEGIN
    INSERT INTO PERSONA(ID_DIRECCION, ID_STATUS_PERSONA, ID_SUPERIOR, NOMBRE, AP_PATERNO, AP_MATERNO, FECHA_NACIMIENTO, CURP, TIPO_PERSONA, FOTO)
    VALUES (V_ID_DIRECCION, V_ID_STATUS_PERSONA, V_ID_SUPERIOR, V_NOMBRE, V_AP_PATERNO, V_AP_MATERNO, V_FECHA_NACIMIENTO, V_CURP, V_TIPO_PERSONA, V_FOTO)
    RETURNING ID_PERSONA INTO ID;
  RETURN ID;
END;
$$
LANGUAGE plpgsql;

--SELECT INSERTA_PERSONA(1,1,NULL,'Ricardo Daniel', 'García', 'Aguilar', '1994-01-20', 'fafafafafafa', 'S', 'fake');
