CREATE OR REPLACE FUNCTION INSERTA_PERSONA(
  IN ID_DIRECCION INTEGER,
  IN ID_STATUS_PERSONA INTEGER,
  IN ID_SUPERIOR INTEGER,
  IN ID_PUESTO INTEGER,
  IN NOMBRE VARCHAR(120),
  IN AP_PATERNO VARCHAR(120),
  IN AP_MATERNO VARCHAR(120),
  IN FECHA_NACIMIENTO DATE,
  IN CURP VARCHAR(18),
  IN FECHA_INGRESO DATE
)
  RETURNS INTEGER AS
$$
DECLARE
  ID PERSONA.ID_PERSONA%TYPE;
  V_ID_DIRECCION ALIAS FOR $1;
  V_ID_STATUS_PERSONA ALIAS FOR $2;
  V_ID_SUPERIOR  ALIAS FOR $3;
  V_ID_PUESTO  ALIAS FOR $4;
  V_NOMBRE ALIAS FOR $5;
  V_AP_PATERNO ALIAS FOR $6;
  V_AP_MATERNO ALIAS FOR $7;
  V_FECHA_NACIMIENTO ALIAS FOR $8;
  V_CURP ALIAS FOR $9;
  V_FECHA_INGRESO ALIAS FOR $10;
BEGIN
    INSERT INTO PERSONA(ID_DIRECCION, ID_STATUS_PERSONA, ID_SUPERIOR, ID_PUESTO, NOMBRE, AP_PATERNO, AP_MATERNO, FECHA_NACIMIENTO, CURP, FECHA_INGRESO)
    VALUES (V_ID_DIRECCION, V_ID_STATUS_PERSONA, V_ID_SUPERIOR, V_ID_PUESTO, V_NOMBRE, V_AP_PATERNO, V_AP_MATERNO, V_FECHA_NACIMIENTO, V_CURP, V_FECHA_INGRESO)
    RETURNING ID_PERSONA INTO ID;
  RETURN ID;
END;
$$
LANGUAGE plpgsql;

--SELECT INSERTA_PERSONA(1,1,NULL,1,'Ricardo Daniel', 'García', 'Aguilar', '1994-01-20', 'fafafafafafa', '2016-11-01');
