CREATE OR REPLACE FUNCTION INSERTA_EDUCACION(
  IN ID_GRADO INTEGER,
  IN ID_ORGANIZACION INTEGER,
  IN NOMBRE VARCHAR(120),
  IN DESCRIPCION VARCHAR(240)
)
  RETURNS INTEGER AS
$$
DECLARE
  ID EDUCACION.ID_EDUCACION%TYPE;
  V_ID_GRADO  ALIAS FOR $1;
  V_ID_ORGANIZACION  ALIAS FOR $2;
  V_NOMBRE  ALIAS FOR $3;
  V_DESCRIPCION ALIAS FOR $4;
BEGIN
  INSERT INTO EDUCACION(ID_GRADO, ID_ORGANIZACION, NOMBRE, DESCRIPCION) VALUES (V_ID_GRADO, V_ID_ORGANIZACION, V_NOMBRE, V_DESCRIPCION) RETURNING ID_EDUCACION INTO ID;
  RETURN ID;
END;
$$
LANGUAGE plpgsql;

--SELECT INSERTA_EDUCACION(3,1, 'Maestria en Ciencias de la computación', 'blablablabla');
