CREATE OR REPLACE FUNCTION INSERTA_ASISTENCIA(
  IN V_ID_PERSONA INTEGER,
  IN V_HORA_ENTRADA TIMESTAMP,
  IN V_HORA_SALIDA TIMESTAMP
)
  RETURNS INTEGER AS
$$
DECLARE
  ID ASISTENCIA.ID_ASISTENCIA%TYPE;
  V_ID_PERSONA  ALIAS FOR $1;
  V_HORA_ENTRADA ALIAS FOR $2;
  V_HORA_SALIDA ALIAS FOR $3;
BEGIN
  INSERT INTO ASISTENCIA(ID_PERSONA, HORA_ENTRADA, HORA_SALIDA)
  VALUES (V_ID_PERSONA, V_HORA_ENTRADA, V_HORA_SALIDA)
  RETURNING ID_ASISTENCIA INTO ID;
  RETURN ID;
END;
$$
LANGUAGE plpgsql;

--SELECT INSERTA_ASISTENCIA(1, '2016-12-05 14:53:09', '2016-12-05 18:05:54');
