CREATE OR REPLACE FUNCTION INSERTA_DIRECCION(
  IN V_ID_COLONIA INTEGER,
  IN CALLE VARCHAR(120),
  IN NUM_INTERIOR VARCHAR(4),
  IN NUM_EXTERIOR VARCHAR(4)
)
  RETURNS INTEGER AS
$$
DECLARE
  ID DIRECCION.ID_DIRECCION%TYPE;
  V_ID_COLONIA ALIAS FOR $1;
  V_CALLE ALIAS FOR $2;
  V_NUM_INTERIOR  ALIAS FOR $3;
  V_NUM_EXTERIOR  ALIAS FOR $4;
BEGIN
  INSERT INTO DIRECCION(ID_COLONIA, CALLE, NUM_EXTERIOR, NUM_INTERIOR)
  VALUES (V_ID_COLONIA, V_CALLE, V_NUM_INTERIOR, V_NUM_EXTERIOR) RETURNING ID_DIRECCION INTO ID;
  RETURN ID;
END;
$$
LANGUAGE plpgsql;

--SELECT INSERTA_DIRECCION(1, 'Hueso', 11, 21);
