CREATE OR REPLACE FUNCTION INSERTA_MUNICIPIO(
  IN V_ID_ESTADO INTEGER,
  IN V_MUNICIPIO VARCHAR(100)
)
  RETURNS INTEGER AS
$$
DECLARE
  ID MUNICIPIO.ID_MUNICIPIO%TYPE;
  V_ID_ESTADO  ALIAS FOR $1;
  NOMBRE_MUNICIPIO ALIAS FOR $2;
BEGIN
  INSERT INTO MUNICIPIO(ID_ESTADO, NOMBRE) VALUES (V_ID_ESTADO, NOMBRE_MUNICIPIO) RETURNING ID_MUNICIPIO INTO ID;
  RETURN ID;
END;
$$
LANGUAGE plpgsql;
