--Vista que muestra la el nombre del personal con el prefijo adecuado a su grado de estudios, todo dentro de un string 
CREATE OR REPLACE VIEW view_admin_grado_personal
(ID_PERSONA, GRADO_NOMBRE_COMPLETO)
AS
SELECT P.ID_PERSONA,
    CONCAT_WS(' ', G.ABREVIACION, P.NOMBRE, P.AP_PATERNO, P.AP_MATERNO) AS GRADO_NOMBRE_COMPLETO
FROM PERSONA P
LEFT OUTER JOIN EDUCACION_PERSONA EP
ON P.ID_PERSONA = EP.ID_PERSONA
LEFT OUTER JOIN EDUCACION E
ON E.ID_EDUCACION = EP.ID_EDUCACION
LEFT OUTER JOIN GRADO G
ON G.ID_GRADO = E.ID_GRADO
WHERE P.TIPO_PERSONA IN ('E', 'S', 'P') AND
EP.ID_EDUCACION_PERSONA = (SELECT MAX(EP1.ID_EDUCACION_PERSONA) FROM EDUCACION_PERSONA EP1 WHERE EP1.ID_PERSONA = P.ID_PERSONA)
OR EP.ID_EDUCACION_PERSONA IS NULL
ORDER BY P.ID_PERSONA ASC;


SELECT * FROM view_admin_grado_personal;
