--VISTA QUE DETALLA LA INFORMACION DE ASISTENCIA DE LOS EMPLEADOS
CREATE OR REPLACE VIEW view_admin_asistencia
(ID_PERSONA, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, ID_ASISTENCIA, DIA, HORA_ENTRADA, HORA_SALIDA, TOTAL)
AS
SELECT P.ID_PERSONA, P.NOMBRE, P.AP_PATERNO AS APELLIDO_PATERNO,
P.AP_MATERNO AS APELLIDO_MATERNO, A.ID_ASISTENCIA,
TO_DATE(TO_CHAR(A.HORA_ENTRADA, 'DD/MM/YYYY'::TEXT), 'DD/MM/YYYY'::TEXT) AS DIA,
TO_CHAR(A.HORA_ENTRADA, 'HH24:MI:SS'::TEXT) AS ENTRADA,
TO_CHAR(A.HORA_SALIDA, 'HH24:MI:SS'::TEXT) AS SALIDA,
(A.HORA_SALIDA - A.HORA_ENTRADA) AS TOTAL
FROM (PERSONA P
JOIN ASISTENCIA A
ON ((P.ID_PERSONA = A.ID_PERSONA)));

SELECT * FROM VIEW_ADMIN_ASISTENCIA;
