--VISTA QUE MUESTRA TODOS LOS GRADOS DE EDUCACION DISPONIBLES
CREATE OR REPLACE VIEW view_admin_educacion
(ID_ORGANIZACION, ORGANIZACION, ID_EDUCACION, NOMBRE_EDUCACION, GRADO)
AS
SELECT O.ID_ORGANIZACION, O.NOMBRE, E.ID_EDUCACION, E.NOMBRE, G.NOMBRE
FROM ORGANIZACION O
INNER JOIN EDUCACION E
ON O.ID_ORGANIZACION = E.ID_ORGANIZACION
INNER JOIN GRADO G
ON E.ID_GRADO = G.ID_GRADO;

SELECT * FROM VIEW_ADMIN_EDUCACION;
