--VISTA QUE MUESTRA LA INFORMACION DE LOS USUARIOS DE CADA EMPLEADO
CREATE OR REPLACE VIEW view_admin_usuario
(ID_EMPLEADO, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FOTO, USUARIO, ROL)
AS
SELECT P.ID_PERSONA, P.NOMBRE, P.AP_PATERNO, P.AP_MATERNO, P.FOTO, U.USUARIO, R.NOMBRE
FROM PERSONA P
INNER JOIN USUARIO U
ON P.ID_PERSONA = U.ID_PERSONA
INNER JOIN ROL R
ON U.ID_ROL = R.ID_ROL;


SELECT * FROM view_admin_usuarios;
