CREATE OR REPLACE VIEW view_admin_servicio
(ID_SERVICIO, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, CURP, FECHA_INGRESO, STATUS, FECHA_FIN)
AS
SELECT P.ID_PERSONA, P.NOMBRE, P.AP_PATERNO, P.AP_MATERNO, P.FECHA_NACIMIENTO, P.CURP, P.FECHA_INGRESO, S.NOMBRE, SE.FECHA_FIN
FROM PERSONA P
INNER JOIN SERVICIO SE
ON P.ID_PERSONA = SE.ID_PERSONA
JOIN STATUS_PERSONA S
ON P.ID_STATUS_PERSONA = S.ID_STATUS_PERSONA;

SELECT * FROM view_admin_servicio;
