--VISTA QUE MUESTRA LA INFORMACION DE TODOS LOS EMPLEADOS, ASI COMO SU ULTIMO PUESTO
--EL SUBQUERY ES UTILIZADO APARA AVEGIGUAR CUAL ES EL ULTIMO PUESTO DE CADA EMPLEADO
--Vista que muestra la informacion de los empleados
CREATE OR REPLACE VIEW view_admin_empleado
(ID_PERSONA, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, TELEFONOS, CORREOS,
	FECHA_NACIMIENTO, CURP, FOTO, NUMERO_EMPLEADO, RFC,
	ID_DIRECCION, CALLE, NUM_INTERIOR, NUM_EXTERIOR, COLONIA, CP,
	MUNICIPIO, ESTADO,
	STATUS, ID_PUESTO, PUESTO, FECHA_INICIO, ID_SUBDEPARTAMENTO,
	SUBDEPARTAMENTO, ID_DEPARTAMENTO, DEPARTAMENTO,
	USUARIO, PASSWORD, ID_ROL, ROL, ABREVIACION_ROL, ID_EDUCACION, ULTIMO_GRADO_ESTUDIOS, ID_GRADO, GRADO
)
AS
SELECT P.ID_PERSONA, P.NOMBRE, P.AP_PATERNO, P.AP_MATERNO,
	(SELECT string_agg(T1.NUMERO, ', ') FROM TELEFONO T1 WHERE T1.ID_PERSONA = P.ID_PERSONA) AS TELEFONOS, --concatenacion de los telefonos
	(SELECT string_agg(C1.CORREO, ', ') FROM CORREO C1 WHERE C1.ID_PERSONA = P.ID_PERSONA) AS CORREOS, 	--concatenacion de los correos
	P.FECHA_NACIMIENTO, P.CURP, P.FOTO, E.NUMERO_EMPLEADO, E.RFC,
	DI.ID_DIRECCION, DI.CALLE, DI.NUM_INTERIOR, DI.NUM_EXTERIOR, CO.NOMBRE AS COLONIA, CO.CP,
	MU.NOMBRE AS MUNICIPIO, ES.NOMBRE AS ESTADO,
	S.NOMBRE AS STATUS, PU.ID_PUESTO, PU.NOMBRE AS PUESTO, PP.FECHA_INICIO, SU.ID_SUBDEPARTAMENTO,
	SU.NOMBRE AS SUBDEPARTAMENTO, DE.ID_DEPARTAMENTO, DE.NOMBRE AS DEPARTAMENTO,
	US.USUARIO, US.PASSWORD, RO.ID_ROL, RO.NOMBRE, RO.ABREVIACION,  ED.ID_EDUCACION, ED.NOMBRE AS ULTIMO_GRADO_ESTUDIOS, GR.ID_GRADO, GR.NOMBRE AS GRADO
FROM PERSONA P
INNER JOIN EMPLEADO E
ON P.ID_PERSONA = E.ID_PERSONA
INNER JOIN STATUS_PERSONA S
ON P.ID_STATUS_PERSONA = S.ID_STATUS_PERSONA
INNER JOIN DIRECCION DI
ON P.ID_DIRECCION = DI.ID_DIRECCION
INNER JOIN COLONIA CO
ON DI.ID_COLONIA = CO.ID_COLONIA
INNER JOIN MUNICIPIO MU
ON CO.ID_MUNICIPIO = MU.ID_MUNICIPIO
INNER JOIN ESTADO ES
ON MU.ID_ESTADO = ES.ID_ESTADO
INNER JOIN PUESTO_PERSONA PP
ON P.ID_PERSONA = PP.ID_PERSONA
INNER JOIN PUESTO PU
ON PP.ID_PUESTO = PU.ID_PUESTO
INNER JOIN SUBDEPARTAMENTO SU
ON PU.ID_SUBDEPARTAMENTO = SU.ID_SUBDEPARTAMENTO
INNER JOIN DEPARTAMENTO DE
ON SU.ID_DEPARTAMENTO = DE.ID_DEPARTAMENTO
INNER JOIN USUARIO AS US
ON P.ID_PERSONA = US.ID_PERSONA
INNER JOIN ROL AS RO
ON US.ID_ROL = RO.ID_ROL
INNER JOIN EDUCACION_PERSONA EP
ON EP.ID_PERSONA = P.ID_PERSONA
INNER JOIN EDUCACION ED
ON EP.ID_EDUCACION = ED.ID_EDUCACION
INNER JOIN GRADO GR
ON ED.ID_GRADO = GR.ID_GRADO
WHERE P.TIPO_PERSONA = 'E'
AND PP.ID_PUESTO_PERSONA =
	(SELECT MAX(ID_PUESTO_PERSONA) FROM PUESTO_PERSONA WHERE ID_PERSONA = P.ID_PERSONA)
AND EP.ID_EDUCACION_PERSONA =
	(SELECT MAX(ID_EDUCACION_PERSONA) FROM EDUCACION_PERSONA WHERE ID_PERSONA = P.ID_PERSONA)
;

--SELECT * FROM VIEW_ADMIN_EMPLEADO;
