--VISTA QUE MUESTRA LA INFORMACION DE LAS PERSONAS EN PRACTICAS PROFESIONALES
--EN ESTE PUNTO SE DESCONOCE LA INFORMACION RELACIONADA CON LOS PRACTICANTES POR LO QUE SE OMITE
--EL JOIN CON LA TABLA DE PRACTICAS PROFESIONALES
CREATE OR REPLACE VIEW view_admin_practicas
(ID_PRACTICAS, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, TELEFONOS, CORREOS, FECHA_NACIMIENTO, CURP, STATUS)
AS
SELECT P.ID_PERSONA, P.NOMBRE, P.AP_PATERNO, P.AP_MATERNO,
	(SELECT string_agg(T1.NUMERO, ', ') FROM TELEFONO T1 WHERE T1.ID_PERSONA = P.ID_PERSONA) AS TELEFONOS, --concatenacion de los telefonos
	(SELECT string_agg(C1.CORREO, ', ') FROM CORREO C1 WHERE C1.ID_PERSONA = P.ID_PERSONA) AS CORREOS, 	--concatenacion de los correos
	P.FECHA_NACIMIENTO, P.CURP, S.NOMBRE
FROM PERSONA P
--INNER JOIN PRACTICAS PR
--ON P.ID_PERSONA = PR.ID_PERSONA
JOIN STATUS_PERSONA S
ON P.ID_STATUS_PERSONA = S.ID_STATUS_PERSONA
WHERE TIPO_PERSONA = 'P';


SELECT * FROM view_admin_practicas;
