CREATE OR REPLACE VIEW view_admin_puestos
(ID_PUESTO, NOMBRE, DESCRIPCION, CLAVE, TIPO, STATUS)
AS
SELECT P.NOMBRE, P.DESCRIPCION, P.CLAVE, TP.NOMBRE, SP.NOMBRE
FROM PUESTO P
INNER JOIN TIPO_PUESTO TP
ON P.ID_TIPO_PUESTO = TP.ID_TIPO_PUESTO
JOIN STATUS_PUESTO SP
ON P.ID_STATUS_PUESTO = SP.ID_STATUS_PUESTO;

--SELECT * FROM VIEW_ADMIN_PUESTOS;
