CREATE OR REPLACE VIEW view_admin_empleado
(ID_EMPLEADO, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, CURP, FECHA_INGRESO, NUMERO_EMPELADO, RFC, STATUS)
AS
SELECT P.ID_PERSONA, P.NOMBRE, P.AP_PATERNO, P.AP_MATERNO, P.FECHA_NACIMIENTO, P.CURP, P.FECHA_INGRESO, E.NUMERO_EMPLEADO, E.RFC, S.NOMBRE
FROM PERSONA P
INNER JOIN EMPLEADO E
ON P.ID_PERSONA = E.ID_PERSONA
JOIN STATUS_PERSONA S
ON P.ID_STATUS_PERSONA = S.ID_STATUS_PERSONA;

--SELECT * FROM view_admin_empleado;
