--VISTA QUE MUESTRA LA INFORMACION DE EL ULTIMO PUESTO PARA CADA EMPLEADO
CREATE OR REPLACE VIEW view_admin_personal_puestos
(ID_EMPLEADO, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, ID_PUESTO, PUESTO,
    FECHA_INICIO, ID_SUPERIOR, ID_SUBDEPARTAMENTO, SUBDEPARTAMENTO, ID_DEPARTAMENTO, DEPARTAMENTO)
AS
SELECT P.ID_PERSONA, P.NOMBRE, P.AP_PATERNO, P.AP_MATERNO, PU.ID_PUESTO, PU.NOMBRE,
    PP.FECHA_INICIO, P.ID_SUPERIOR, SU.ID_SUBDEPARTAMENTO, SU.NOMBRE, DE.ID_DEPARTAMENTO, DE.NOMBRE
FROM PERSONA P
INNER JOIN PUESTO_PERSONA PP
ON P.ID_PERSONA = PP.ID_PERSONA
INNER JOIN PUESTO PU
ON PP.ID_PUESTO = PU.ID_PUESTO
INNER JOIN SUBDEPARTAMENTO SU
ON SU.ID_SUBDEPARTAMENTO = PU.ID_SUBDEPARTAMENTO
INNER JOIN DEPARTAMENTO DE
ON DE.ID_DEPARTAMENTO = SU.ID_DEPARTAMENTO
WHERE PP.ID_PUESTO_PERSONA = (SELECT MAX(PP1.ID_PUESTO_PERSONA) FROM PUESTO_PERSONA PP1 WHERE PP1.ID_PERSONA = P.ID_PERSONA)
ORDER BY P.ID_PERSONA ASC;


SELECT * FROM view_admin_personal_puestos;
