CREATE OR REPLACE VIEW view_admin_direccion
(ID_PERSONA, NOMBRE, AP_PATERNO, AP_MATERNO, CALLE, NUMERO_INTERIOR, NUMERO_EXTERIOR, COLONIA, CP, MUNICIPIO, ESTADO)
AS
SELECT ID_PERSONA, P.NOMBRE, P.AP_PATERNO, AP_MATERNO, D.CALLE, D.NUM_INTERIOR, D.NUM_EXTERIOR, C.NOMBRE, C.CP, M.NOMBRE, E.NOMBRE
FROM PERSONA P
INNER JOIN DIRECCION D
ON P.ID_DIRECCION = D.ID_DIRECCION
JOIN COLONIA C
ON D.ID_COLONIA = C.ID_COLONIA
JOIN MUNICIPIO M
ON C.ID_MUNICIPIO = M.ID_MUNICIPIO
JOIN ESTADO E
ON M.ID_ESTADO = E.ID_ESTADO;

SELECT * FROM view_admin_direccion;
