--vista que muestra toda la informacion de los servidores sociales
CREATE OR REPLACE VIEW view_admin_servicio
(ID_SERVICIO, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, TELEFONOS, CORREOS, FECHA_NACIMIENTO, CURP, STATUS)
AS
SELECT P.ID_PERSONA, P.NOMBRE, P.AP_PATERNO, P.AP_MATERNO,
	(SELECT string_agg(T1.NUMERO, ', ') FROM TELEFONO T1 WHERE T1.ID_PERSONA = P.ID_PERSONA) AS TELEFONOS, --concatenacion de los telefonos
	(SELECT string_agg(C1.CORREO, ', ') FROM CORREO C1 WHERE C1.ID_PERSONA = P.ID_PERSONA) AS CORREOS, 	--concatenacion de los correos
	P.FECHA_NACIMIENTO, P.CURP, S.NOMBRE
FROM PERSONA P
INNER JOIN SERVICIO SE
ON P.ID_PERSONA = SE.ID_PERSONA
INNER JOIN STATUS_PERSONA S
ON P.ID_STATUS_PERSONA = S.ID_STATUS_PERSONA
WHERE P.TIPO_PERSONA = 'S';

SELECT * FROM view_admin_servicio;
