--FUNCION QUE MUESTRA LA DIRECCION DE UNA PERSONA
CREATE OR REPLACE FUNCTION FUNC_MUESTRA_DIRECCION(
  IN V_ID_PERSONA INTEGER
)
  --RETURNS view_admin_direccion AS --SIGNIFICA QUE RETORNA UN RECORD DEL TIPO DE LA VISTA VIEW_ADMIN_DIRECCION
  RETURNS RECORD AS
$$
DECLARE
    V_ID_PERSONA  ALIAS FOR $1;
    V_ROW RECORD;
    --V_ROW view_admin_direccion%ROWTYPE;
BEGIN
SELECT ID_PERSONA, P.NOMBRE, P.AP_PATERNO, AP_MATERNO, D.CALLE, D.NUM_INTERIOR, D.NUM_EXTERIOR, C.NOMBRE, C.CP, M.NOMBRE, E.NOMBRE
    INTO V_ROW
    FROM PERSONA P
    INNER JOIN DIRECCION D
    ON P.ID_DIRECCION = D.ID_DIRECCION
    JOIN COLONIA C
    ON D.ID_COLONIA = C.ID_COLONIA
    JOIN MUNICIPIO M
    ON C.ID_MUNICIPIO = M.ID_MUNICIPIO
    JOIN ESTADO E
    ON M.ID_ESTADO = E.ID_ESTADO
    WHERE ID_PERSONA = V_ID_PERSONA;
    RETURN V_ROW;
END;
$$
LANGUAGE plpgsql;
--SELECT FUNC_MUESTRA_DIRECCION(1);
