--Funcion recibe id, regresa información de una persona en especifico
CREATE OR REPLACE FUNCTION FUNC_MUESTRA_PERSONA(
  IN V_ID_PERSONA INTEGER
)
  RETURNS RECORD AS
$$
DECLARE
    V_ID_PERSONA  ALIAS FOR $1;
    V_ROW RECORD;
    V_ID_ULTIMO_TELEFONO TELEFONO.ID_TELEFONO%TYPE;
    V_ID_ULTIMO_CORREO CORREO.ID_CORREO%TYPE;
BEGIN
    SELECT MAX(ID_TELEFONO)  INTO V_ID_ULTIMO_TELEFONO FROM TELEFONO WHERE ID_PERSONA = V_ID_PERSONA;
    SELECT MAX(ID_CORREO)  INTO V_ID_ULTIMO_CORREO FROM CORREO WHERE ID_PERSONA = V_ID_PERSONA;
SELECT P.ID_PERSONA, P.NOMBRE, P.AP_PATERNO, P.AP_MATERNO, P.FECHA_NACIMIENTO, P.CURP, P.FECHA_INGRESO, T.NUMERO, C.CORREO, U.USUARIO, PU.NOMBRE, S.NOMBRE
    INTO V_ROW
    FROM PERSONA P
    INNER JOIN USUARIO U
    ON P.ID_PERSONA = U.ID_PERSONA
    JOIN PUESTO PU
    ON P.ID_PUESTO = PU.ID_PUESTO
    JOIN STATUS_PERSONA S
    ON S.ID_STATUS_PERSONA = P.ID_STATUS_PERSONA
    LEFT OUTER JOIN TELEFONO T
    ON P.ID_PERSONA = T.ID_PERSONA
    LEFT OUTER JOIN CORREO C
    ON P.ID_PERSONA = C.ID_PERSONA
    WHERE P.ID_PERSONA = V_ID_PERSONA
    AND T.ID_TELEFONO = V_ID_ULTIMO_TELEFONO
    AND C.ID_CORREO = V_ID_ULTIMO_CORREO;
    RETURN V_ROW;
END;
$$
LANGUAGE plpgsql;

--SELECT FUNC_MUESTRA_PERSONA(1);
