--FUNCION QUE MUESTRA LOS CURSOS QUE HA TOMADO UN TRABAJADOR
--ENTRADAS: ID DE LA PERSONA DE LA QUE SE DESEA SABER LOS CURSOS (INTEGER), NOMBRE DEL CURSOR DONDE SE ALMACENARAN LOS DATOS
--SALIDA: CURSOR CON LA INFORMACION DE LOS CURSOS OBTENIDA
CREATE OR REPLACE FUNCTION func_cursos(ID integer, ref refcursor)
RETURNS refcursor AS $$
 BEGIN
   OPEN ref FOR SELECT CP.ID_CURSO_PERSONA, C.NOMBRE, C.DESCRIPCION, CP.FECHA_INICIO, CP.FECHA_FIN, O.NOMBRE, CP.PROBATORIO
        FROM CURSOS C
        JOIN CURSOS_PERSONA CP
        ON C.ID_CURSO = CP.ID_CURSO
        JOIN ORGANIZACION O
        ON C.ID_ORGANIZACION = O.ID_ORGANIZACION
        WHERE ID_PERSONA = ID
        ORDER BY CP.ID_CURSO_PERSONA ASC;
   RETURN ref;
 END;
 $$ LANGUAGE plpgsql;

--COMANDOS NECESARIOS PARA VER LOS RESULTADOS DE LA FUNCION
BEGIN;
      SELECT FUNC_CURSOS(1, 'CURSOS');
      FETCH ALL IN "CURSOS";
COMMIT;
