--FUNCION QUE RECIBE COMO PARAMETRO EL ID DE UN EMPLEADO
--MUESTRA TODA LA INFORMACION DEL EMPLEADO
--LA INFORMACION QUE DESPLIEGA DE LA EDUCACION CORRESPONDE AL ULTIMO CURSO OBTENIDO
CREATE OR REPLACE FUNCTION FUNC_MUESTRA_EMPLEADO(
  IN V_ID_PERSONA INTEGER
)
  RETURNS RECORD AS
$$
DECLARE
    V_ID_PERSONA  ALIAS FOR $1;
    V_ROW RECORD;
    V_ID_EDUCACION INTEGER;

BEGIN
    SELECT MAX(ID_EDUCACION_PERSONA) INTO V_ID_EDUCACION FROM EDUCACION_PERSONA EP1 WHERE  EP1.ID_PERSONA = V_ID_PERSONA; --ULTIMO GRADO DE ESTUDIOS
    SELECT P.ID_PERSONA, P.NOMBRE, P.AP_PATERNO, P.AP_MATERNO, P.FECHA_NACIMIENTO,
        P.CURP, P.FOTO, E.NUMERO_EMPLEADO, E.RFC,
        (SELECT string_agg(T1.NUMERO, ', ') FROM TELEFONO T1 WHERE T1.ID_PERSONA = V_ID_PERSONA) AS TELEFONOS, --concatenacion de los telefonos
    	(SELECT string_agg(C1.CORREO, ', ') FROM CORREO C1 WHERE C1.ID_PERSONA = V_ID_PERSONA) AS CORREOS, 	--concatenacion de los correos
        PU.NOMBRE AS PUESTO, S.NOMBRE AS STATUS,
        G.NOMBRE AS GRADO, ED.NOMBRE AS MAXIMO_GRADO_ESTUDIOS,
        C.NOMBRE AS COLONIA, M.NOMBRE AS MUNICIPIO,
        ES.NOMBRE AS ESTADO, U.USUARIO, U.PASSWORD
        INTO V_ROW
        FROM PERSONA P
        JOIN EMPLEADO E
        ON P.ID_PERSONA = E.ID_PERSONA
        JOIN USUARIO U
        ON P.ID_PERSONA = U.ID_PERSONA
        JOIN PUESTO_PERSONA PP
        ON P.ID_PERSONA = PP.ID_PERSONA
        JOIN PUESTO PU
        ON PP.ID_PUESTO = PU.ID_PUESTO
        JOIN STATUS_PERSONA S
        ON S.ID_STATUS_PERSONA = P.ID_STATUS_PERSONA
        JOIN DIRECCION D
        ON P.ID_DIRECCION = D.ID_DIRECCION
        JOIN COLONIA C
        ON D.ID_COLONIA = C.ID_COLONIA
        JOIN MUNICIPIO M
        ON C.ID_MUNICIPIO = M.ID_MUNICIPIO
        JOIN ESTADO ES
        ON M.ID_ESTADO = ES.ID_ESTADO
        JOIN EDUCACION_PERSONA EP
        ON EP.ID_PERSONA = P.ID_PERSONA
        JOIN EDUCACION ED
        ON EP.ID_EDUCACION = ED.ID_EDUCACION
        JOIN GRADO G
        ON ED.ID_GRADO = G.ID_GRADO
        WHERE P.TIPO_PERSONA = 'E'
        AND P.ID_PERSONA = V_ID_PERSONA
        AND EP.ID_EDUCACION_PERSONA = V_ID_EDUCACION;
        RETURN V_ROW;
END;
$$
LANGUAGE plpgsql;

--SELECT FUNC_MUESTRA_EMPLEADO(8);
