CREATE OR REPLACE FUNCTION func_educacion(id integer, ref refcursor)
RETURNS refcursor AS $$
 BEGIN
   OPEN ref FOR SELECT EP.ID_EDUCACION_PERSONA, E.NOMBRE, E.DESCRIPCION, EP.FECHA_INICIO, EP.FECHA_FIN, O.NOMBRE, G.NOMBRE
        FROM EDUCACION E
        JOIN EDUCACION_PERSONA EP
        ON E.ID_EDUCACION = EP.ID_EDUCACION
        JOIN ORGANIZACION O
        ON E.ID_ORGANIZACION = O.ID_ORGANIZACION
        JOIN GRADO G
        ON G.ID_GRADO = E.ID_GRADO
        WHERE ID_PERSONA = ID
        ORDER BY EP.ID_EDUCACION_PERSONA ASC;
   RETURN ref;
 END;
 $$ LANGUAGE plpgsql;

 BEGIN;
     SELECT FUNC_EDUCACION(1, 'EDUCACION');
     FETCH ALL IN "EDUCACION";
 COMMIT;
