--FUNCION QUE MUESTRA LA INFORMACION TRABAJADORES POR DEPARTAMENTO
--ENTRADA: ID DEL DEPARTAMENTO  (INTEGER), NOMBRE DEL CURSOR DONDE ALMACENARA LA INFORMACION
--SALIDA: CURSOR CON LA INFORMACION DE LOS TRABAJADORES ORDENADA POR SU SUBDEPARTAMENTO
CREATE OR REPLACE FUNCTION func_empleados_depto(
    IN id integer,
    IN ref refcursor)
RETURNS refcursor AS $$
 BEGIN
   OPEN ref FOR SELECT P.ID_PERSONA, P.NOMBRE, P.AP_PATERNO, P.AP_MATERNO, P.ID_SUPERIOR, SP.NOMBRE AS STATUS,
            P.FOTO, S.NOMBRE AS SUBDIRECCION,PU.NOMBRE AS PUESTO,PP.FECHA_INICIO
        FROM PERSONA P
        INNER JOIN PUESTO_PERSONA PP
        ON P.ID_PERSONA = PP.ID_PERSONA
        INNER JOIN STATUS_PERSONA SP
        ON P.ID_STATUS_PERSONA = SP.ID_STATUS_PERSONA
        INNER JOIN PUESTO PU
        ON PP.ID_PUESTO = PU.ID_PUESTO
        INNER JOIN SUBDEPARTAMENTO S
        ON S.ID_SUBDEPARTAMENTO = PU.ID_SUBDEPARTAMENTO
        INNER JOIN DEPARTAMENTO D
        ON S.ID_DEPARTAMENTO = D.ID_DEPARTAMENTO
        WHERE D.ID_DEPARTAMENTO = ID
        ORDER BY(S.ID_SUBDEPARTAMENTO) ASC;
   RETURN ref;
 END;
 $$ LANGUAGE plpgsql;

 BEGIN;
     SELECT FUNC_EMPLEADOS_DEPTO(2, 'EMPLEADOS');
     FETCH ALL IN "EMPLEADOS";
 COMMIT;
