CREATE OR REPLACE FUNCTION func_puesto(ID integer, ref refcursor)
RETURNS refcursor AS $$
 BEGIN
   OPEN ref FOR SELECT P.ID_PUESTO, P.NOMBRE, P.DESCRIPCION, P.CLAVE, TP.NOMBRE, SP.NOMBRE
        FROM PUESTO P
        JOIN TIPO_PUESTO TP
        ON P.ID_TIPO_PUESTO = TP.ID_TIPO_PUESTO
        JOIN STATUS_PUESTO SP
        ON P.ID_STATUS_PUESTO = SP.ID_STATUS_PUESTO
        JOIN PERSONA
        WHERE P.EID_PERSONA = ID
        ORDER BY P.ID_PUESTO ASC;
   RETURN ref;
 END;
 $$ LANGUAGE plpgsql;

BEGIN;
      SELECT FUNC_PUESTO(1, 'PUESTO');
      FETCH ALL IN "PUESTO";
COMMIT;
