CREATE OR REPLACE FUNCTION func_cursos(ID integer, ref refcursor)
RETURNS refcursor AS $$
 BEGIN
   OPEN ref FOR SELECT CP.ID_CURSO_PERSONA, C.NOMBRE, C.DESCRIPCION, CP.FECHA_INICIO, CP.FECHA_FIN, O.NOMBRE
        FROM CURSO C
        JOIN CURSO_PERSONA CP
        ON C.ID_CURSO = CP.ID_CURSO
        JOIN ORGANIZACION O
        ON C.ID_ORGANIZACION = O.ID_ORGANIZACION
        WHERE ID_PERSONA = ID
        ORDER BY CP.ID_CURSO_PERSONA ASC;
   RETURN ref;
 END;
 $$ LANGUAGE plpgsql;

 --BEGIN;
--      SELECT FUNC_CURSOS(1, 'CURSOS');
--      FETCH ALL IN "CURSOS";
 -- COMMIT;
