--FUNCION PARA CALCULAR LAS HORAS TRABAJADAS
--ENTRADAS: ID_PERSONA (INTEGER), FECHA DE INICIO (DATE) PARA EL CALCULO, FECHA DE FIN DE CALCULO (DATE)
--SALIDA: TOTAL DE HORAS TRABAJADAS (INTERVAL)
CREATE OR REPLACE FUNCTION FUNC_MUESTRA_ASISTENCIA(
  IN ID INTEGER,
  IN V_FECHA_INICIO DATE,
  IN V_FECHA_FIN DATE,
  IN REF REFCURSOR
)
    RETURNS refcursor AS $$

DECLARE
    V_ID_PERSONA  ALIAS FOR $1;
    V_FECHA_INICIO ALIAS FOR $2;
    V_FECHA_FIN ALIAS FOR $3;
BEGIN
    OPEN ref FOR SELECT DIA, HORA_ENTRADA, HORA_SALIDA, TOTAL
    FROM VIEW_ADMIN_ASISTENCIA
    WHERE ID_PERSONA = ID
    AND (DIA >= V_FECHA_INICIO OR DIA <= V_FECHA_FIN)
    ORDER BY ID_ASISTENCIA ASC;
RETURN ref;
END;
$$
LANGUAGE plpgsql;

BEGIN;
    SELECT FUNC_MUESTRA_ASISTENCIA(1, '2016-12-06', '2016-12-08', 'ASISTENCIA');
    FETCH ALL IN "ASISTENCIA";
COMMIT;
