--FUNCION QUE CAMBIA EL ULTIMO PUESTO DE UNA PERSONA
--ENTRADAS: ID DE LA PERSONA
--  ID DEL NUEVO PUESTO A INSERTAR
--  FECHA DEL ASCENSO
--SALIDAS: ID DEL NUEVO PUESTO_PERSONA QUE SE INSERTO
CREATE OR REPLACE FUNCTION func_ascenso(
  IN V_ID_PERSONA INTEGER,
  IN V_ID_NUEVO_PUESTO INTEGER,
  IN FECHA_ASCENSO DATE
)
  RETURNS INTEGER AS
$$
DECLARE
  ID PUESTO_PERSONA.ID_PUESTO_PERSONA%TYPE;
  V_ID_PERSONA  ALIAS FOR $1;
  V_ID_NUEVO_PUESTO ALIAS FOR $2;
  V_FECHA_ASCENSO ALIAS FOR $3;
  V_ID INTEGER;
BEGIN
  V_ID := (SELECT MAX(ID_PUESTO_PERSONA) FROM PUESTO_PERSONA WHERE ID_PERSONA = 1);
  UPDATE PUESTO_PERSONA
  SET FECHA_FIN = V_FECHA_ASCENSO
  WHERE ID_PERSONA = V_ID_PERSONA
  AND ID_PUESTO_PERSONA = V_ID;
  ID := INSERTA_PUESTO_PERSONA(V_ID_PERSONA, V_ID_NUEVO_PUESTO, V_FECHA_ASCENSO);
  RETURN ID;
END;
$$
LANGUAGE plpgsql;

SELECT func_ascenso(1, 7, '2017-01-12');
